[package]
name = "tim7775/debug-random"
description = "A wrapper around Roblox's Random class that enables users to serialize and set the state of the Random object"
license = "MIT"
authors = ["Tim7775"]
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["*"]
include = ["src", "src/init.luau", "default.project.json", "LICENSE.md", "README.md", "wally.toml"]
homepage = "https://tim7775.github.io/DebugRandom/api/DebugRandom"
repository = "https://github.com/Tim7775/DebugRandom.git"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@=0.4.1"
