name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Lint
        run: selene ./src

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Run StyLua check
        run: stylua --check ./src
